### ISSUE TITLE
How to set the max ack timeout in leshan server to be greater than 60s?

### ISSUE THREAD

**Issue by sathysreenath** [eclipse-leshan/leshan#1432]
### Question

Hi 

We are working on a project that requires ack timeout to be greater than 60 seconds for leshan server. We are able to set the ack timeout in californium 3 properties, but always get an error that the ack timeout should be less than the max ack timeout. (Maximum ack timeout 60000ms must not be less than ack timeout 70000ms!). We tried adding the max ack timeout to californium 3 properties file and starting leshan ([WARN] Ignore COAP.MAX_ACK_TIMEOUT, no configuration definition available!), but that does not help either. The only way we were able to do it was by adding the max ack timeout in leshan server demo java file like below. There is  probably a better way to do this without changing the java file, we need help for this.

Configuration serverCoapConfig = endpointsBuilder.createDefaultConfiguration();
serverCoapConfig.set(CoapConfig.MAX_ACK_TIMEOUT, 70, TimeUnit.SECONDS);

Thank you.

**Comment by jvermillard** [comment]
You can set the timeout in the send() API: https://github.com/eclipse/leshan/blob/master/leshan-server-core/src/main/java/org/eclipse/leshan/server/LeshanServer.java#L462

I tested it for up to two hours for a very long clockwise requests

**Comment by sbernard31** [comment]
I guess you are using Leshan `2.0.0-M11` or `master`  as you are talking about `endpointsBuilder`.

> but always get an error that the ack timeout should be less than the max ack timeout.

I tried to reproduce it with **leshan-server-demo**  but I didn't get any error :thinking: 
When do you get this error exactly ?

> We tried adding the max ack timeout to californium 3 properties file and starting leshan ([WARN] Ignore COAP.MAX_ACK_TIMEOUT, no configuration definition available!)

You should not have to do that, this looks like a Californium bug....
MAX_ACK_TIMEOUT seems to not be added to CoapConfig, see  : 
https://github.com/eclipse-californium/californium/blob/e927def9c72d062d750cc7dca441afc1f5b33fd7/californium-core/src/main/java/org/eclipse/californium/core/config/CoapConfig.java#L794-L852

So you should [open an issue at Californium repository](https://github.com/eclipse-californium/californium/issues/new). 

> The only way we were able to do it was by adding the max ack timeout in leshan server demo java file like below. There is probably a better way to do this without changing the java file, we need help for this.

Not sure as this seems to be a bug.

**Comment by sathysreenath** [comment]
Thanks for the quick reply, yes the latest master. The error occurs only when we have set the ack timeout to be greater than default max ack timeout (60s) and the leshan sever does not bootup. I will file an issue with californium to get the max ack timeout added into californium properties. Thanks so much for your help.

java -jar leshan-server-demo.jar
2023-03-31 10:48:30,318 CoapOscoreServerEndpointFactory [WARN] Experimental OSCORE feature is enabled.
Unable to create and start server ...

java.lang.IllegalStateException: Maximum ack timeout 60000ms must not be less than ack timeout 70000ms!
        at org.eclipse.californium.core.network.stack.ReliabilityLayerParameters$Builder.check(ReliabilityLayerParameters.java:281)
        at org.eclipse.californium.core.network.stack.ReliabilityLayerParameters$Builder.applyConfig(ReliabilityLayerParameters.java:172)
        at org.eclipse.californium.core.network.stack.ReliabilityLayer.<init>(ReliabilityLayer.java:89)
        at org.eclipse.californium.core.network.stack.CongestionControlLayer.newImplementation(CongestionControlLayer.java:704)
        at org.eclipse.californium.oscore.OSCoreUdpStack.<init>(OSCoreUdpStack.java:54)
        at org.eclipse.californium.oscore.OSCoreCoapStackFactory.createCoapStack(OSCoreCoapStackFactory.java:54)
        at org.eclipse.californium.core.network.CoapEndpoint.<init>(CoapEndpoint.java:424)
        at org.eclipse.californium.core.network.CoapEndpoint$Builder.build(CoapEndpoint.java:1806)
        at org.eclipse.leshan.server.californium.endpoint.coap.CoapServerEndpointFactory.createCoapEndpoint(CoapServerEndpointFactory.java:115)
        at org.eclipse.leshan.server.californium.endpoint.CaliforniumServerEndpointsProvider.createEndpoints(CaliforniumServerEndpointsProvider.java:123)
        at org.eclipse.leshan.server.LeshanServer.<init>(LeshanServer.java:163)
        at org.eclipse.leshan.server.LeshanServerBuilder.createServer(LeshanServerBuilder.java:320)
        at org.eclipse.leshan.server.LeshanServerBuilder.build(LeshanServerBuilder.java:299)
        at org.eclipse.leshan.server.demo.LeshanServerDemo.createLeshanServer(LeshanServerDemo.java:254)
        at org.eclipse.leshan.server.demo.LeshanServerDemo.main(LeshanServerDemo.java:98)

**Comment by sathysreenath** [comment]
I have opened a issue in californium. Thanks so much for all your help.

https://github.com/eclipse-californium/californium/issues/2127
