### ISSUE TITLE
I cannot read client information because of time out

### ISSUE THREAD

**Issue by huny0501** [eclipse-leshan/leshan#1476]
### Question

I am using leshan demo.
When I tested to read device information test on my local pc, it worked very well.
but, when I tested same test on aws server, it didnt work because of time out.
Do you have any expected point? (e.g firewall.. something wrong development...)
timeout occured lwm2mServer.send method
I tried to test without timeout time, but i got the same response.
it is my source code. if you need more information, request me plz

```java
public static String readResouce(LeshanServer lwm2mServer, String deviceEndpoint, int objectID, int objectInstanceID, int resourceID) throws InterruptedException {
                int timeout = 10000;
		ReadRequest readDeviceObject = new ReadRequest(ContentFormat.SENML_JSON, "/"+ objectID + "/" + objectInstanceID + "/" + resourceID);
		Registration registration = lwm2mServer.getRegistrationService().getByEndpoint(deviceEndpoint);
		ReadResponse cResponse = lwm2mServer.send(registration, readDeviceObject, timeout);
		LwM2mResource resource = (LwM2mResource) cResponse.getContent();
		return resource.getValue().toString();
	}
```

it is error log
```
2023-07-19 07:57:39.286 DEBUG 6 --- [0.0.0.0:5683[0]] o.e.californium.elements.UDPConnector    : UDPConnector (0.0.0.0:5683) received 237 bytes from XXX.XXX.XXX.XXX:18215
2023-07-19 07:57:39.308 DEBUG 6 --- [pServer(main)#1] o.e.c.c.n.d.SweepDeduplicator            : add exchange for KeyMID[XXX.XXX.XXX.XXX:18215-40428]
2023-07-19 07:57:39.330 DEBUG 6 --- [pServer(main)#1] o.e.l.s.r.RegistrationHandler            : New registration: Registration [registrationDate=Wed Jul 19 07:57:39 UTC 2023, identity=Identity /XXX.XXX.XXX.XXX:18215[unsecure], lifeTimeInSec=300, smsNumber=null, lwM2mVersion=1.1, bindingMode=[U], queueMode=false, endpoint=TEST0001, id=zUD5cbvxgP, objectLinks=[</>;rt=[oma.lwm2m];ct=[CBOR(60), SENML_JSON(110), SENML_CBOR(112), TLV(11542), JSON(11543)], </1>;ver=1.1, </1/0>, </3>;ver=1.2, </3/0>, </4>;ver=1.3, </4/0>, </5>;ver=1.1, </5/0>, </6/0>, </3303>;ver=1.1, </3303/0>, </3442/0>, </20000/0>], additionalRegistrationAttributes={}, rootPath=/, supportedContentFormats=[TLV(11542), JSON(11543), LINK(40), OPAQUE(42), CBOR(60), SENML_JSON(110), SENML_CBOR(112), TEXT(0)], supportedObjects={20000=1.0, 1=1.1, 3442=1.0, 3=1.2, 4=1.3, 5=1.1, 6=1.0, 3303=1.1}, availableInstances=[/1/0, /3/0, /4/0, /5/0, /6/0, /3303/0, /3442/0, /20000/0], lastUpdate=Wed Jul 19 07:57:39 UTC 2023, applicationData={}]
2023-07-19 07:57:39.347 DEBUG 6 --- [pServer(main)#1] o.e.c.c.network.stack.ReliabilityLayer   : Exchange[R1, XXX.XXX.XXX.XXX:18215] send response null-2.01   MID=   -1, Token=null, OptionSet={"Location-Path":["rd","zUD5cbvxgP"]}, <empty data>
2023-07-19 07:57:39.351 DEBUG 6 --- [pServer(main)#1] o.e.californium.core.network.Exchange    : Exchange[R1, XXX.XXX.XXX.XXX:18215, complete]!
2023-07-19 07:57:39.351 DEBUG 6 --- [pServer(main)#1] o.e.californium.core.network.Exchange    : Remote Exchange[R1, XXX.XXX.XXX.XXX:18215, complete] completed ACK-2.01   MID=40428, Token=1C3D976A8DB08922, OptionSet={"Location-Path":["rd","zUD5cbvxgP"]}, <empty data>!
2023-07-19 07:57:39.359 DEBUG 6 --- [0.0.0.0:5683[0]] o.e.californium.elements.UDPConnector    : UDPConnector (Thread[UDP-Sender-0.0.0.0/0.0.0.0:5683[0],5,Californium/Elements]) sent 26 bytes to XXX.XXX.XXX.XXX:18215
2023-07-19 07:57:39.466 DEBUG 6 --- [pServer(main)#1] o.e.l.server.demo.servlet.EventServlet   : Dispatching REGISTRATION event from endpoint TEST0001
##########################lwm2mServer############################ : org.eclipse.leshan.server.californium.LeshanServer@76fea214
##########################deviceEndpoint############################ : TEST0001
2023-07-19 07:57:46.883 DEBUG 6 --- [er(secondary)#2] o.e.c.c.n.d.SweepDeduplicator            : Sweep run took 0ms
2023-07-19 07:57:49.483 DEBUG 6 --- [pServer(main)#1] o.e.l.c.c.CoapSyncRequestObserver        : Synchronous request cancelled CON-GET    MID=   -1, Token=null, OptionSet={"Uri-Path":["5","0","3"], "Accept":"application/cbor"}, canceled <empty data>
2023-07-19 07:57:49.484 ERROR 6 --- [pServer(main)#1] o.e.l.c.californium.LwM2mCoapResource    : Exception while handling request [CON-POST   MID=40428, Token=1C3D976A8DB08922, OptionSet={"Uri-Path":"rd", "Content-Format":"application/link-format", "Uri-Query":["b=U","lwm2m=1.1","lt=300","ep=TEST0001"]}, acked "</>;rt="oma.lwm2m";ct="60 110 11".. 180 bytes] on the resource /rd from Identity /XXX.XXX.XXX.XXX:18215[unsecure]
java.lang.NullPointerException: null
        at com.samsung.kfota.util.InterfaceHandler.readResouce(InterfaceHandler.java:36) ~[classes!/:0.0.1-SNAPSHOT]
        at com.samsung.kfota.dm.handler.KfotaDMHandler.startUpdate(Handler.java:22) ~[classes!/:0.0.1-SNAPSHOT]
        at com.samsung.kfota.dm.controller.KfotaDMApplication.startUpdate(Application.java:277) ~[classes!/:0.0.1-SNAPSHOT]
        at org.eclipse.leshan.server.californium.registration.RegisterResource.handlePOST(RegisterResource.java:115) ~[classes!/:na]
        at org.eclipse.californium.core.CoapResource.handleRequest(CoapResource.java:246) ~[californium-core-3.5.0.jar!/:na]
        at org.eclipse.leshan.core.californium.LwM2mCoapResource.handleRequest(LwM2mCoapResource.java:51) ~[leshan-core-cf-2.0.0-M8.jar!/:na]
        at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverRequest(ServerMessageDeliverer.java:106) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:218) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveRequest(BlockwiseLayer.java:562) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:296) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:140) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.CoapEndpoint$1.receiveRequest(CoapEndpoint.java:302) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.UdpMatcher$2.run(UdpMatcher.java:289) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:290) [element-connector-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.CoapEndpoint$6.run(CoapEndpoint.java:1341) [californium-core-3.5.0.jar!/:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_292]
        at scouter.agent.wrapper.async.WrTask.run(WrTask.java:35) [na:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_292]

>2023-07-19 07:57:49.487 DEBUG 6 --- [pServer(main)#1] o.e.c.c.network.stack.ReliabilityLayer   : Exchange[R1, XXX.XXX.XXX.XXX:18215, complete] send response null-5.00   MID=   -1, Token=null, OptionSet={}, <empty data>
2023-07-19 07:57:49.487 DEBUG 6 --- [pServer(main)#1] o.e.c.c.network.stack.ReliabilityLayer   : Exchange[R1, XXX.XXX.XXX.XXX:18215, complete] prepare retransmission for CON-5.00   MID=   -1, Token=null, OptionSet={}, <empty data>
2023-07-19 07:57:49.490  WARN 6 --- [pServer(main)#1] o.e.c.core.network.stack.BaseCoapStack   : error send response CON-5.00   MID=   -1, Token=1C3D976A8DB08922, OptionSet={}, <empty data>
````

```
org.eclipse.californium.core.network.ExchangeCompleteException: Exchange[R1, XXX.XXX.XXX.XXX:18215, complete] is already complete! CON-5.00   MID=   -1, Token=1C3D976A8DB08922, OptionSet={}, <empty data>
        at org.eclipse.californium.core.network.Exchange.assertIncomplete(Exchange.java:1362) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.InMemoryMessageExchangeStore.registerWithMessageId(InMemoryMessageExchangeStore.java:240) ~[californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.InMemoryMessageExchangeStore.registerOutboundResponse(InMemoryMessageExchangeStore.java:411) ~[californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.UdpMatcher.sendResponse(UdpMatcher.java:161) ~[californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendResponse(CoapEndpoint.java:909) ~[californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendResponse(BaseCoapStack.java:250) ~[californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.ReliabilityLayer.sendResponse(ReliabilityLayer.java:150) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.BlockwiseLayer.sendResponse(BlockwiseLayer.java:767) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.ObserveLayer.sendResponse(ObserveLayer.java:125) ~[californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.AbstractLayer.sendResponse(AbstractLayer.java:74) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.ExchangeCleanupLayer.sendResponse(ExchangeCleanupLayer.java:95) ~[californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.sendResponse(BaseCoapStack.java:208) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.BaseCoapStack.sendResponse(BaseCoapStack.java:113) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.CoapEndpoint.sendResponse(CoapEndpoint.java:702) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.Exchange.sendResponse(Exchange.java:503) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.leshan.core.californium.LwM2mCoapResource.handleRequest(LwM2mCoapResource.java:58) [leshan-core-cf-2.0.0-M8.jar!/:na]
        at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverRequest(ServerMessageDeliverer.java:106) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:218) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveRequest(BlockwiseLayer.java:562) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:296) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:140) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.CoapEndpoint$1.receiveRequest(CoapEndpoint.java:302) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.UdpMatcher$2.run(UdpMatcher.java:289) [californium-core-3.5.0.jar!/:na]
        at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:290) [element-connector-3.5.0.jar!/:na]
        at org.eclipse.californium.core.network.CoapEndpoint$6.run(CoapEndpoint.java:1341) [californium-core-3.5.0.jar!/:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_292]
        at scouter.agent.wrapper.async.WrTask.run(WrTask.java:35) [na:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_292]
```

**Comment by sbernard31** [comment]
```
java.lang.NullPointerException: null
        at com.samsung.kfota.util.InterfaceHandler.readResouce(InterfaceHandler.java:36) ~[classes!/:0.0.1-SNAPSHOT]
        at com.samsung.kfota.dm.handler.KfotaDMHandler.startUpdate(Handler.java:22) ~[classes!/:0.0.1-SNAPSHOT]
        at com.samsung.kfota.dm.controller.KfotaDMApplication.startUpdate(Application.java:277) ~[classes!/:0.0.1-SNAPSHOT]
        at org.eclipse.leshan.server.californium.registration.RegisterResource.handlePOST(RegisterResource.java:115) ~[classes!/:na]
        at org.eclipse.californium.core.CoapResource.handleRequest(CoapResource.java:246) ~[californium-core-3.5.0.jar!/:na]
        at org.eclipse.leshan.core.californium.LwM2mCoapResource.handleRequest(LwM2mCoapResource.java:51) ~[leshan-core-cf-2.0.0-M8.jar!/:na]
```       
:point_up:  It seems you modify `RegisterResource`, not sure exactly why but generally this is much better to just add a `RegistrationListener` using `server.getRegistrationService().addListener( ...)` 

>  Do you have any expected point? (e.g firewall.. something wrong development...)

It could be anything, very hard to say especially if you are modifying leshan code instead of just using it as a library. 

> ReadResponse cResponse = lwm2mServer.send(registration, readDeviceObject, timeout);

I strongly advice to use async API. ( this should avoid the send response exchange cause by your NPE as you don't manage the timeout use case properly...)

**Comment by sbernard31** [comment]
Should we close this issue ?

**Comment by huny0501** [comment]
Ok, thanks for your help

**Comment by huny0501** [comment]
:)
