### ISSUE TITLE
I want to use TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256 cipher suite

### ISSUE THREAD

**Issue by jjangho308** [eclipse-leshan/leshan#1480]
### Question

The client uses the MBEDTLS library and the TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256 cipher suite.
I know that TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256 is not DTLS_RECOMMENDED_CIPHER_SUITES.

That's why I found out that the error log below is occurring.
But I have to use TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256 for leshan server dtls.

I checked the "Californium3.server.properties" file, I checked the guide "If not accepted cipher suits are integrated to be used, switch off." I need a detailed description of the "If not accepted cipher suits are integrated to be used, switch off" guide.

I'm sorry, but it would be nice if you could give me a code level guide.

====================== error log ==============================
2023-07-21 06:06:53.970 DEBUG 6 --- [/0.0.0.0:5684#1] o.e.c.scandium.dtls.ServerHandshaker     : handshake failed dtls-con: CID=F0D8FC100E0B, 211.36.131.104:5449, ongoing handshake , is alive

org.eclipse.californium.scandium.dtls.HandshakeException: Client does not propose a common cipher suite
        at org.eclipse.californium.scandium.dtls.ServerHandshaker.receivedClientHello(ServerHandshaker.java:492) ~[scandium-3.5.0.jar!/:na]
        at org.eclipse.californium.scandium.dtls.ServerHandshaker.doProcessMessage(ServerHandshaker.java:282) ~[scandium-3.5.0.jar!/:na]
        at org.eclipse.californium.scandium.dtls.Handshaker.processNextHandshakeMessages(Handshaker.java:969) ~[scandium-3.5.0.jar!/:na]

**Comment by sbernard31** [comment]
I don't know which version of Leshan you are using but it seems that it depends on californium/scandium 3.5.0.

Looking at last californium release, I understand that ARIA support was added in californium/scandium 3.9.0, see https://projects.eclipse.org/projects/iot.californium/releases/3.9.0. (Maybe @boaks can confirm that)

Currently there is no Leshan release integrating californium/scandium 3.9.0. [It is not plan to integrate it in M12 ](https://github.com/eclipse-leshan/leshan/issues/1468)which is expected very very soon but should be integrated in M13. Note if there is no API/behavior break between californium minor version a solution could be to force to use californium/scandium 3.9.0 in your maven dependencies. This could work but this must be tested. 

Currently Leshan `master` embedded californium/scandium 3.8.0, but 3.9.0 will be integrate in `master` as soon as the M12 release is out.

**Comment by jjangho308** [comment]
"Currently Leshan master embedded californium/scandium 3.8.0, but 3.9.0 will be integrate in master as soon as the M12 release is out."  =====>  When do you expect it to be integrated 3.9?

**Comment by sbernard31** [comment]
I'm waiting for green light from contributors/Users : 
=> https://github.com/eclipse-leshan/leshan/issues/1468#issuecomment-1645163738

(Again note that you can **probably** already use californium 3.9.0 with Leshan just overriding dependencies)

**Comment by jjangho308** [comment]
I will force maven dependencies with scandium 3.9 :) Thank you.

**Comment by sbernard31** [comment]
(I will let you know as soon as it is integrated in `master` in this issue)

**Comment by jjangho308** [comment]
Is there any way to add ARIA cipher suite as code modification other than to upgrade californium/scandium?
I am using leshan 2.0.0-M8, californium/scandium 3.5.0

**Comment by sbernard31** [comment]
> Is there any way to add ARIA cipher suite as code modification other than to upgrade californium/scandium?

I don't think so.

>  I am using leshan 2.0.0-M8, californium/scandium 3.5.0

2.0.0-M8 is affected by security issue, at this day you should at least use 2.0.0-M9, see : https://github.com/eclipse-leshan/leshan/security/policy#versions-security-state

**Comment by boaks** [comment]
> Looking at last californium release, I understand that ARIA support was added in californium/scandium 3.9.0

Please note, that Californium doesn't implement ARIA, it uses ARIA from the JCE. 
Therefore the JCE must supports it.
In my experience, you need to use BouncyCastle, I wasn't able to use it with the openjdk 17.

There will be no "ready to use build" including BouncyCastle. And if you use it, use it with care. 
Read [Californium - Support For Bouncy Castle](https://github.com/eclipse-californium/californium/tree/main/scandium-core#support-for-bouncy-castle).

> Is there any way to add ARIA cipher suite as code modification other than to upgrade californium/scandium?
I am using leshan 2.0.0-M8, californium/scandium 3.5.0

I'm pretty sure, you need to update Californium to 3.9.0. I don't know, If that works with Leshan 2.0.0-M8, you may need to test that.

**Comment by sbernard31** [comment]
cf 3.9.0 is now integrated in `master`.

Let us know if you succed to uses ARIA and let us know if can close the issue too.

**Comment by jjangho308** [comment]
I will test and let you know.

**Comment by jjangho308** [comment]
Californium3.server.properties 파일에 아래와 같이 지정하였더니

DTLS.CIPHER_SUITES=TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256

아래와 같은 error message가 나옵니다. 혹시 CIPHER SUITES를 다른 스펠링으로 입력해야하나요?
확인이 필요합니다.

I specified the following in the Californium3.server.properties file
DTLS.CIPHER_SUITES=TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256

The following error message appears. Do I need to enter CIPHER SUITES in a different spelling?
I need confirmation.

==================================== error message===============================
2023-07-24 04:59:56.901  WARN 6 --- [           main] o.e.l.s.californium.LeshanServerBuilder  : Unable to create DTLS config and so secured endpoint.

java.lang.IllegalStateException: Supported cipher suites must be set either explicitly or implicitly by means of setting the identity or PSK store
        at org.eclipse.californium.scandium.config.DtlsConnectorConfig$Builder.build(DtlsConnectorConfig.java:2341) ~[scandium-3.9.0.jar!/:na]
        at org.eclipse.leshan.server.californium.LeshanServerBuilder.build(LeshanServerBuilder.java:563) ~[leshan-server-cf-2.0.0-M8.jar!/:0.0.1-SNAPSHOT]
        at com.samsung.kfota.dm.controller.KfotaDMApplication.createLeshanServer(KfotaDMApplication.java:225) [classes!/:0.0.1-SNAPSHOT]
        at com.samsung.kfota.dm.controller.KfotaDMApplication.run(KfotaDMApplication.java:97) [classes!/:0.0.1-SNAPSHOT]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) [spring-boot-2.7.5.jar!/:2.7.5]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755) [spring-boot-2.7.5.jar!/:2.7.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.7.5.jar!/:2.7.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-2.7.5.jar!/:2.7.5]

**Comment by boaks** [comment]
You don't use a JCE (Java Cryptography Extension), which supports ARIA.
I already wrote that above. Maybe [Californium - Supporting ARIA Ciphersuite](https://github.com/eclipse-californium/californium/issues/2124) helps.

**Comment by boaks** [comment]
You're welcome!
