### ISSUE TITLE
Send request is not received

### ISSUE THREAD

**Issue by ferrveciana** [eclipse-leshan/leshan#1503]
### Question

2.0.0-M13 / No DTLS

I'm having a similar problem https://github.com/eclipse-leshan/leshan/issues/756, https://github.com/eclipse-leshan/leshan/issues/758, https://github.com/eclipse-leshan/leshan/issues/507. My code is working fine in my machine but not in docker containers.

I'm using the async requests and I also increased the thread count to 4 from both server and client. The docker environment I'm using has 6 cores available which I checked using the `Runtime.getRuntime().availableProcessors()`.

This is my server instantiation:

```java
    public LeshanServer build() {
        final LeshanServerBuilder leshanServerBuilder = new LeshanServerBuilder();
        loadObjectModels(leshanServerBuilder);
        final ThrowingSupplier<URI> uriThrowingSupplier = () -> new URI(COAP, null, host, port, null, null, null);
        final URI uri = Try.supplyOrThrow(uriThrowingSupplier, Lwm2mException.uriNotCorrect());
        final ServerProtocolProvider serverProtocolProvider = new CoapServerProtocolProvider();
        final CaliforniumServerEndpointFactory californiumServerEndpointFactory = serverProtocolProvider.createDefaultEndpointFactory(uri);
        log.info("NUMBER OF CORES:".concat(Integer.toString(Runtime.getRuntime().availableProcessors())));
        final Configuration config = new Configuration();
        config.set(CoapConfig.PROTOCOL_STAGE_THREAD_COUNT, 4);
        final CaliforniumServerEndpointsProvider californiumServerEndpointsProvider = new CaliforniumServerEndpointsProvider.Builder(serverProtocolProvider)
                .setConfiguration(config)
                .addEndpoint(californiumServerEndpointFactory)
                .build();
        leshanServerBuilder.setEndpointsProvider(californiumServerEndpointsProvider);
        return leshanServerBuilder.build();
    }
```

Client:
```java
    @Bean
    public void leshanClient() {
        // load the core models (Security, Server, Device ...)
        final List<ObjectModel> models = ObjectLoader.loadAllDefault();
        final String[] modelPaths = new String[]{OBJECT_ID + ".xml"};
        final Executor executor = () -> models.addAll(ObjectLoader.loadDdfResources("/OMA_model/", modelPaths));
        Try.executeOrThrow(executor, new ESipaException(LWM2M_OBJECT_LOADER_ERROR, DETAILED_LWM2M_OBJECT_LOADER_ERROR));

        final LeshanClientBuilder leshanClientBuilder = new LeshanClientBuilder(eimId);
        final ClientProtocolProvider clientProtocolProvider = new CoapClientProtocolProvider();
        final org.eclipse.californium.elements.config.Configuration config = new org.eclipse.californium.elements.config.Configuration();
        clientProtocolProvider.applyDefaultValue(config);
        config.set(CoapConfig.PROTOCOL_STAGE_THREAD_COUNT, 4);
        log.info("NUMBER OF CORES:".concat(Integer.toString(Runtime.getRuntime().availableProcessors())));

        final ThrowingSupplier<InetAddress> inetAddressSupplier = () -> InetAddress.getByName(clientUrl);
        final InetAddress inetAddress = Try.supplyOrThrow(inetAddressSupplier, new ESipaException(ESipaException.LWM2M_CONNECT_ERROR, ESipaException.LWM2M_CONNECT_ERROR));
        final CaliforniumClientEndpointsProvider californiumServerEndpointsProvider = new CaliforniumClientEndpointsProvider
                .Builder(clientProtocolProvider)
                .setConfiguration(config)
                .setClientAddress(inetAddress)
                .build();

        final ObjectsInitializer initializer = objectsInitializer(models);
        leshanClientBuilder.setObjects(initializer.createAll());
        final LeshanClient client = leshanClientBuilder
                .setEndpointsProvider(californiumServerEndpointsProvider)
                .build();
        client.start();
    }
```

sendRequest client side:
```java
    public void execute(final PublishRequest publishRequest) {
        final String message = publishRequest.payload();
        log.info("[Lwm2mSender] Sending message [{}] to server.", message);

        final SendService sendService = leshanClient.getSendService();
        final ResponseCallback<SendResponse> responseCallback = getSendResponseCallback();
        final ErrorCallback errorCallback = errorCallback();
        log.info(lwM2mServer.toString());
        sendService.sendData(lwM2mServer, ContentFormat.SENML_JSON, List.of(PATH), 120000, responseCallback, errorCallback);
    }

    private static ResponseCallback<SendResponse> getSendResponseCallback() {
        return response -> {
            if (response.isSuccess()) {
                log.info("[Lwm2mSender] message successfully sent to server.");
            } else {
                log.info("[Lwm2mSender] error in responseCallback");
            }
        };
    }
```

SendRequest listener:
```java
    @Override
    public void dataReceived(final Registration registration, final TimestampedLwM2mNodes data, final SendRequest request) {
        log.info("[Lwm2mSendListener] New send message received " + registration.getEndpoint());
        CommunicationProtocolThreadLocal.setCommunicationProtocol(CommunicationProtocolEnum.LWM2M);
        final LwM2mPath lwM2mPath = new LwM2mPath(3443, 0, 3);
        final LwM2mSingleResource resource = (LwM2mSingleResource) data.getNodes().get(lwM2mPath);
        final byte[] payloadBytes = (byte[]) resource.getValue();
        final byte[] hexEncodedPayloadMessage = Hex.encode(payloadBytes);
        final String payload = StringUtil.parseByteArray(hexEncodedPayloadMessage);
        sendRequestReceived.accept(payload);
    }

    @Override
    public void onError(Registration registration, Exception error) {
        log.info("[Lwm2mSendListener] Error received " + registration.getEndpoint());
    }
```

Logs indicate Im sending the SendRequest, but I'm never receiving it. Client side error:

```
mock                    | 2023-09-01T07:47:30.641Z ERROR 6 --- [pServer(main)#2] o.e.l.c.californium.LwM2mCoapResource    : Exception while handling request [CON-PUT    MID=52781, Token=F862BBA84EB90817, OptionSet={"Uri-Path":["3443","0","2"], "Content-Format":"application/octet-stream"}, BF 4F 2D BF 52 2A 5C 04 A5 A6 A8 84 5A 10 12 34 56 78 90 12 34 56 78 90 12 34 56 78 90 12 82 10..48 bytes] on the resource /3443 from IpPeer [peerAddress=/172.18.0.8:5683, identity=Identity [unsecure=/172.18.0.8:5683]]
mock                    |
mock                    | java.lang.NullPointerException: Cannot invoke "org.eclipse.leshan.client.endpoint.LwM2mClientEndpoint.send(org.eclipse.leshan.client.servers.LwM2mServer, org.eclipse.leshan.core.request.UplinkRequest, org.eclipse.leshan.core.response.ResponseCallback, org.eclipse.leshan.core.response.ErrorCallback, long)" because "endpoint" is null
mock                    |       at org.eclipse.leshan.client.request.DefaultUplinkRequestSender.send(DefaultUplinkRequestSender.java:45) ~[leshan-client-core-2.0.0-M13.jar!/:na]
mock                    |       at org.eclipse.leshan.client.send.DataSenderManager.sendData(DataSenderManager.java:115) ~[leshan-client-core-2.0.0-M13.jar!/:na]
mock                    |       at org.eclipse.leshan.client.LeshanClient$2.sendData(LeshanClient.java:269) ~[leshan-client-core-2.0.0-M13.jar!/:na]
mock                    |       at com.gi_de.eim.mock.server.ipa.lwm2m.Lwm2mSender.execute(Lwm2mSender.java:45) ~[classes!/:1.0.0-SNAPSHOT]
mock                    |       at com.gi_de.eim.mock.server.ipa.lwm2m.Lwm2mESipaObject.processRequest(Lwm2mESipaObject.java:94) ~[classes!/:1.0.0-SNAPSHOT]
mock                    |       at com.gi_de.eim.mock.server.ipa.lwm2m.Lwm2mESipaObject.write(Lwm2mESipaObject.java:80) ~[classes!/:1.0.0-SNAPSHOT]
mock                    |       at org.eclipse.leshan.client.resource.ObjectEnabler.doWrite(ObjectEnabler.java:292) ~[leshan-client-core-2.0.0-M13.jar!/:na]
mock                    |       at org.eclipse.leshan.client.resource.BaseObjectEnabler.write(BaseObjectEnabler.java:263) ~[leshan-client-core-2.0.0-M13.jar!/:na]
mock                    |       at org.eclipse.leshan.client.request.DefaultDownlinkReceiver$RequestHandler.visit(DefaultDownlinkReceiver.java:141) ~[leshan-client-core-2.0.0-M13.jar!/:na]
mock                    |       at org.eclipse.leshan.core.request.WriteRequest.accept(WriteRequest.java:500) ~[leshan-core-2.0.0-M13.jar!/:2.0.0-M13]
mock                    |       at org.eclipse.leshan.client.request.DefaultDownlinkReceiver.requestReceived(DefaultDownlinkReceiver.java:97) ~[leshan-client-core-2.0.0-M13.jar!/:na]
mock                    |       at org.eclipse.leshan.client.californium.object.ObjectResource.handlePUT(ObjectResource.java:271) ~[leshan-client-cf-2.0.0-M13.jar!/:na]
mock                    |       at org.eclipse.californium.core.CoapResource.handleRequest(CoapResource.java:264) ~[californium-core-3.9.0.jar!/:na]
mock                    |       at org.eclipse.leshan.core.californium.LwM2mCoapResource.handleRequest(LwM2mCoapResource.java:58) ~[leshan-core-cf-2.0.0-M13.jar!/:na]
mock                    |       at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverRequest(ServerMessageDeliverer.java:133) ~[californium-core-3.9.0.jar!/:na]
mock                    |       at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:204) ~[californium-core-3.9.0.jar!/:na]
mock                    |       at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84) ~[californium-core-3.9.0.jar!/:na]
mock                    |       at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84) ~[californium-core-3.9.0.jar!/:na]
mock                    |       at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveRequest(BlockwiseLayer.java:578) ~[californium-core-3.9.0.jar!/:na]
mock                    |       at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:296) ~[californium-core-3.9.0.jar!/:na]
mock                    |       at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84) ~[californium-core-3.9.0.jar!/:na]
mock                    |       at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:126) ~[californium-core-3.9.0.jar!/:na]
mock                    |       at org.eclipse.californium.core.network.CoapEndpoint$1.receiveRequest(CoapEndpoint.java:310) ~[californium-core-3.9.0.jar!/:na]
mock                    |       at org.eclipse.californium.core.network.UdpMatcher$2.run(UdpMatcher.java:289) ~[californium-core-3.9.0.jar!/:na]
mock                    |       at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:292) ~[element-connector-3.9.0.jar!/:na]
mock                    |       at org.eclipse.californium.core.network.CoapEndpoint$6.run(CoapEndpoint.java:1367) ~[californium-core-3.9.0.jar!/:na]
mock                    |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
mock                    |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
mock                    |       at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

last server logs are:
```
2023-09-01T07:47:30.575Z TRACE 6 --- [ntContainer#3-1] o.e.l.c.node.codec.DefaultLwM2mEncoder : Encoding node LwM2mSingleResource [id=2, value=48Bytes, type=OPAQUE] for path /3443/0/2 and format OPAQUE(42)
2023-09-01T07:47:30.576Z TRACE 6 --- [ntContainer#3-1] o.e.l.c.n.c.o.LwM2mNodeOpaqueEncoder : Encoding resource LwM2mSingleResource [id=2, value=48Bytes, type=OPAQUE] into Bytes(OPAQUE format)
2023-09-01T07:47:30.577Z TRACE 6 --- [ntContainer#3-1] o.e.l.c.node.codec.DefaultLwM2mEncoder : Encoded node LwM2mSingleResource [id=2, value=48Bytes, type=OPAQUE]: [-65, 79, 45, -65, 82, 42, 92, 4, -91, -90, -88, -124, 90, 16, 18, 52, 86, 120, -112, 18, 52, 86, 120, -112, 18, 52, 86, 120, -112, 18, -126, 16, 62, 45, 9, 3, -77, 62, 77, -97, -112, -23, 106, -84, 21, 35, 87, 89]
2023-09-01T07:47:30.578Z TRACE 6 --- [pServer(main)#4] o.e.l.c.c.CoapAsyncRequestObserver : Schedule Cleaning Task for CON-PUT MID=52781, Token=F862BBA84EB90817, OptionSet={"Uri-Path":["3443","0","2"], "Content-Format":"application/octet-stream"}, BF 4F 2D BF 52 2A 5C 04 A5 A6 A8 84 5A 10 12 34 56 78 90 12 34 56 78 90 12 34 56 78 90 12 82 10..48 bytes
2023-09-01T07:47:30.667Z DEBUG 6 --- [pServer(main)#1] o.e.l.c.c.CoapAsyncRequestObserver : Received coap response: ACK-5.00 MID=52781, Token=F862BBA84EB90817, OptionSet={}, <empty data> for CON-PUT MID=52781, Token=F862BBA84EB90817, OptionSet={"Uri-Path":["3443","0","2"], "Content-Format":"application/octet-stream"}, acked BF 4F 2D BF 52 2A 5C 04 A5 A6 A8 84 5A 10 12 34 56 78 90 12 34 56 78 90 12 34 56 78 90 12 82 10..48 bytes
2023-09-01T07:47:30.673Z INFO 6 --- [pServer(main)#1] c.g.e.d.c.i.ipa.lwm2m.EimLeshanServer : [EimLeshanServer] WriteResponse received from Registration 2
2023-09-01T07:47:30.675Z ERROR 6 --- [pServer(main)#1] c.g.e.d.c.i.ipa.lwm2m.EimLeshanServer : Failed to write: INTERNAL_SERVER_ERROR(500)
```

I have a mix between read, write and send requests but even though the last error here is a writeRequest INTERNAL_SERVER_ERROR, my guess is that the problem comes from the sendRequest which is never received in the first place. Also before this error a writeRequest is done correctly. Maybe the thread configuration done wrong?

**Comment by sbernard31** [comment]
At first sight, the only issue I see is : 
```
2023-09-01T07:47:30.641Z ERROR 6 --- [pServer(main)#2] o.e.l.c.californium.LwM2mCoapResource    : Exception while handling request [CON-PUT    MID=52781, Token=F862BBA84EB90817, OptionSet={"Uri-Path":["3443","0","2"], "Content-Format":"application/octet-stream"}, BF 4F 2D BF 52 2A 5C 04 A5 A6 A8 84 5A 10 12 34 56 78 90 12 34 56 78 90 12 34 56 78 90 12 82 10..48 bytes] on the resource /3443 from IpPeer [peerAddress=/172.18.0.8:5683, identity=Identity [unsecure=/172.18.0.8:5683]]
java.lang.NullPointerException: Cannot invoke "org.eclipse.leshan.client.endpoint.LwM2mClientEndpoint.send(org.eclipse.leshan.client.servers.LwM2mServer, org.eclipse.leshan.core.request.UplinkRequest, org.eclipse.leshan.core.response.ResponseCallback, org.eclipse.leshan.core.response.ErrorCallback, long)" because "endpoint" is null
      at org.eclipse.leshan.client.request.DefaultUplinkRequestSender.send(DefaultUplinkRequestSender.java:45) ~[leshan-client-core-2.0.0-M13.jar!/:na]
      at org.eclipse.leshan.client.send.DataSenderManager.sendData(DataSenderManager.java:115) ~[leshan-client-core-2.0.0-M13.jar!/:na]
      at org.eclipse.leshan.client.LeshanClient$2.sendData(LeshanClient.java:269) ~[leshan-client-core-2.0.0-M13.jar!/:na]
```

Looking at corresponding code in `DefaultUplinkRequestSender` :
```java
@Override
public <T extends LwM2mResponse> void send(LwM2mServer server, UplinkRequest<T> request, long timeoutInMs,
        ResponseCallback<T> responseCallback, ErrorCallback errorCallback) {
    LwM2mClientEndpoint endpoint = endpointsProvider.getEndpoint(server);
    endpoint.send(server, request, responseCallback, errorCallback, timeoutInMs);
}
```
I guess that endpointsProvider is not able to retrieve corresponding endpoint for the given server.


Looking at  `CaliforniumClientEndpointsProvider` which support only one active server : 
```java
@Override
public LwM2mClientEndpoint getEndpoint(LwM2mServer server) {
    if (currentServer.equals(server)) {
        return endpoint;
    }
    return null;
}
 ```
 I guess the server you pass is not equals to the current one. 
 
 I see a : `log.info(lwM2mServer.toString());` in your code. What do you get ?

**Comment by ferrveciana** [comment]
COAP://server:5683[LWM2M_SERVER 2]

server being the server address mapped with docker-compose

**Comment by sbernard31** [comment]
I tried to look at the code and I can not understand how it can be different of null and also not equals to currentServer ... :thinking:

**Comment by ferrveciana** [comment]
I checked the readRequest controller which works fine and the log output of the lwM2mServer.toString() is the same.
You don't think it could be a thread problem?
I found a bit confusing the thread configuration and I am not sure I did it right on both sides.. For example, I could set the Configuration object on the client side on both CaliforniumClientEndpointsProvider as well as in californiumServerEndpointFactory, didn't know the difference.

**Comment by sbernard31** [comment]
Californium Configuration is confusing to me too. I tried to deal with it when I created Californium implementations of `LwM2mClientEndpointsProvider` but I'm not sure how to make it better ... 
 - `Configuration` of `CaliforniumClientEndpointsProvider` will set `Configuraiton` of Californium `CoapServer`. This will also be used as default one to create all endpoints attached to this Provider/CoapServer.
- At server side you can also set the `Configuration`  at EndpointsProvider level  (like for client) OR at `*ServerEndpointFactory` level which will set Configuration of  Californium `Endpoint`. This allow to have different configuration than the "default one" for a given endpoint. 
(I'm not sure I'm clear :sweat_smile: )

**Probably not related to your problem,** I see you create `Configuration` like this : `new Configuration()`.
This is not the recommended way, if you create a new Configuration you should use `endpointsBuilder.createDefaultConfiguration()` unless you know exactly what you do.
You can have a look at https://github.com/eclipse-leshan/leshan/pull/1407 to see alternative API.

**Comment by sbernard31** [comment]
Looking at you stacktrace, 
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.leshan.client.endpoint.LwM2mClientEndpoint.send(org.eclipse.leshan.client.servers.LwM2mServer, org.eclipse.leshan.core.request.UplinkRequest, org.eclipse.leshan.core.response.ResponseCallback, org.eclipse.leshan.core.response.ErrorCallback, long)" because "endpoint" is null
      at org.eclipse.leshan.client.request.DefaultUplinkRequestSender.send(DefaultUplinkRequestSender.java:45) ~[leshan-client-core-2.0.0-M13.jar!/:na]
      at org.eclipse.leshan.client.send.DataSenderManager.sendData(DataSenderManager.java:115) ~[leshan-client-core-2.0.0-M13.jar!/:na]
      at org.eclipse.leshan.client.LeshanClient$2.sendData(LeshanClient.java:269) ~[leshan-client-core-2.0.0-M13.jar!/:na]
      at com.gi_de.eim.mock.server.ipa.lwm2m.Lwm2mSender.execute(Lwm2mSender.java:45) ~[classes!/:1.0.0-SNAPSHOT]
      at com.gi_de.eim.mock.server.ipa.lwm2m.Lwm2mESipaObject.processRequest(Lwm2mESipaObject.java:94) ~[classes!/:1.0.0-SNAPSHOT]
      at com.gi_de.eim.mock.server.ipa.lwm2m.Lwm2mESipaObject.write(Lwm2mESipaObject.java:80) ~[classes!/:1.0.0-SNAPSHOT]
      at org.eclipse.leshan.client.resource.ObjectEnabler.doWrite(ObjectEnabler.java:292) ~[leshan-client-core-2.0.0-M13.jar!/:na]
      at org.eclipse.leshan.client.resource.BaseObjectEnabler.write(BaseObjectEnabler.java:263) ~[leshan-client-core-2.0.0-M13.jar!/:na]
```

Note sure this is a good idea to do the `sendData` in same thread that the one who execute the write. 

But I don't think this is related to the NPE ... :disappointed:

**Comment by ferrveciana** [comment]
No good news so far.
I changed the configuration to `endpointsBuilder.createDefaultConfiguration()` as you mentioned but It wasn't the problem.

About this:
> Note sure this is a good idea to do the sendData in same thread that the one who execute the write.

I understand the problem with this but, what should be the correct way to approach it? I need to get messages both ways between the server and the client and the natural thing to do is to sending after receiving, in the same execution thread. I tried creating a new java thread like `new Thread(this::processRequest).start();` _(sendRequest is inside this processRequest)_.But I'm not sure this makes much of a difference. 

As you said, the NPE error is not related to that. :(

**Comment by sbernard31** [comment]
Looking at your client code, I can not see where you create your mandatory object (Security,  Server,  Device)
I guess this is in your `objectsInitializer(models);` method. 
  
  Looking at this a bit more, I still don't understand how it's possible that ` CaliforniumClientEndpointsProvider.getEndpoint(server)` return `null`.  (https://github.com/eclipse-leshan/leshan/issues/1503#issuecomment-1702379272)
  
  I guess you should investigate more about this,  adding more log to understand what happens here.

**Comment by ferrveciana** [comment]
Found the error!
During the lwm2mServer instantiation for the sendService, I was setting the InetAddress in the IpPeer to the clientUrl instead of the serverUrl. The Uri was correct but not this field.
When testing this in my local machine since both of them were localhost, there wasn't any error.

Stupid mistake. I was wondering if there is a reason why both the URI and the IpPeer need the host&port. Is there any case this hosts and ports could be different?

**Comment by sbernard31** [comment]
> Stupid mistake. I was wondering if there is a reason why both the URI and the IpPeer need the host&port. Is there any case this hosts and ports could be different?

I 'm not sure I get you ? :thinking:

**Comment by ferrveciana** [comment]
```
        InetAddress inetAddress =InetAddress.getByName(serverUrl);
        InetSocketAddress inetSocketAddress = new InetSocketAddress(inetAddress, serverPort);
        LwM2mIdentity identity = new SocketIdentity(inetSocketAddress);
        IpPeer ipPeer = new IpPeer(inetSocketAddress, identity);
        URI uri = new URI(COAP.getName(), null, serverUrl, serverPort, null, null, null);
        LwM2mServer lwM2mServer = new LwM2mServer(ipPeer, Long.parseLong(eimId), uri);
```

as you can see serverUrl and serverPort are given twice. Why is this necessary?

**Comment by sbernard31** [comment]
Is it your code ?  So you create the LwM2mServer on your own ?

Generally this is not what you should do. You should use a LwM2mServer that you get from method. e.g. : 
 - org.eclipse.leshan.client.resource.ObjectEnabler.doWrite(LwM2mServer, WriteRequest)
 - org.eclipse.leshan.client.LeshanClient.getRegisteredServers()
 
 
>  as you can see serverUrl and serverPort are given twice. Why is this necessary?

Internally, in Leshan URI is the value store in Security Object and LwM2mPeer are more the real network data.
