### ISSUE TITLE
NullPointerException occurs in running a tutorial code building a simple LwM2M Client

### ISSUE THREAD

**Issue by JeonghyunJoo** [eclipse-leshan/leshan#1559]
### Question

I am new to this leshan LwM2M library so please understand me even if my question is a stupid one.

I tried to strictly follow the instructions given by https://github.com/eclipse-leshan/leshan/wiki/Getting-Started-:-Client but I failed to run the tutorial code.

I added specified maven dependencies with 2.0.0-m14 for the leshan library version under the <dependencies> tag in my pom.xml. 

I put the example code in my main function, resulting in the following code:
```java
package com.jjh.maven.leshan_client_example;

import org.eclipse.leshan.client.LeshanClient;
import org.eclipse.leshan.client.LeshanClientBuilder;
import org.eclipse.leshan.client.endpoint.LwM2mClientEndpointsProvider;

public class App 
{
    public static void main( String[] args )
    {
    	String endpoint = "..." ; // choose an endpoint name
    	LeshanClientBuilder builder = new LeshanClientBuilder(endpoint);
    	LeshanClient client = builder.build();
    	client.start();
    }
}
```

It successfully compiled but gave me a `NullPointerException` with endpointsProvider. The full error message looks like this:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.eclipse.leshan.client.endpoint.LwM2mClientEndpointsProvider.init(org.eclipse.leshan.client.resource.LwM2mObjectTree, org.eclipse.leshan.client.request.DownlinkRequestReceiver, org.eclipse.leshan.client.endpoint.ClientEndpointToolbox)" because "endpointsProvider" is null
	at org.eclipse.leshan.client.LeshanClient.<init>(LeshanClient.java:123)
	at org.eclipse.leshan.client.LeshanClientBuilder.createLeshanClient(LeshanClientBuilder.java:364)
	at org.eclipse.leshan.client.LeshanClientBuilder.build(LeshanClientBuilder.java:328)
	at com.jjh.maven.leshan_client_example.App.main(App.java:13)
 ```

In my understanding it seems that I need to call `builder.setEndpointsProviders` explicitly as `builder.endpointsProvider` is never initialized with the example code.

Is the tutorial code incomplete? or did I miss something?
If the example code is incomplete, can I ask where I can find a working and concise tutorial code for building a simple client (expecting much simpler code than `LeshanClientDemo.java`)

Thanks in advance.

**Comment by JeonghyunJoo** [comment]
Thanks @sbernard31

You are right! I could make it run by modifying the Leshan version from 2.0.0-m14 to 1.5.0
