### ISSUE TITLE
Cannot run multiple server demo instances

### ISSUE THREAD

**Issue by PFnord** [eclipse-leshan/leshan#1589]
### Question

Hello, I recently updated some of my leshan servers and was blocked from running multiple instances of the same server (on different ports). I specifically spawn multiple instances of server-demo and bsserver-demo but recently stumbled upon this when running 2 server-demo at the same time:

```
java.lang.IllegalStateException: Unable to start java-coap endpoint
	at org.eclipse.leshan.transport.javacoap.server.endpoint.JavaCoapServerEndpointsProvider.start(JavaCoapServerEndpointsProvider.java:121)
	at org.eclipse.leshan.server.endpoint.DefaultCompositeServerEndpointsProvider.start(DefaultCompositeServerEndpointsProvider.java:80)
	at org.eclipse.leshan.server.LeshanServer.start(LeshanServer.java:259)
	at org.eclipse.leshan.server.demo.LeshanServerDemo.main(LeshanServerDemo.java:126)
Caused by: java.net.BindException: Address already in use (Bind failed)
	at java.base/java.net.PlainDatagramSocketImpl.bind0(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:135)
	at java.base/java.net.DatagramSocket.bind(DatagramSocket.java:394)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:244)
	at com.mbed.coap.transport.udp.DatagramSocketTransport.createSocket(DatagramSocketTransport.java:105)
	at com.mbed.coap.transport.udp.DatagramSocketTransport.start(DatagramSocketTransport.java:77)
	at com.mbed.coap.server.CoapServer.start(CoapServer.java:64)
	at org.eclipse.leshan.transport.javacoap.server.endpoint.JavaCoapServerEndpointsProvider.start(JavaCoapServerEndpointsProvider.java:119)
```

**How to reproduce**
`master`
build server-demo and bsserver-demo 
```
java -jar leshan-server-demo/target/leshan-server-demo-2.0.0-SNAPSHOT-jar-with-dependencies.jar -lp 5600 -wp 8000 -slp 5601 && java -jar leshan-server-demo/target/leshan-server-demo-2.0.0-SNAPSHOT-jar-with-dependencies.jar -lp 5602 -wp 8001 -slp 5603
```

**Workaround**
I've workarounded this issue by reverting this commit [edc4edf]( https://github.com/eclipse-leshan/leshan/commit/edc4edf06a983fa9d8471cf3711a397bb600d7c6) 

If this behavior is correct and intentional, what is the correct way to build leshan and be able to run 2+ server-demo at the same time (on different ports)?

**Comment by sbernard31** [comment]
by default **leshan-server-demo** create 3 endpoints : 
- `coap://leshan.eclipseprojects.io:5683`: CoAP over UDP endpoint based on Californium library with very experimental support of OSCORE.
 - `coaps://leshan.eclipseprojects.io:5684`: CoAP over DTLS endpoint based on Californium/Scandium library.
 - `coap://leshan.eclipseprojects.io:5685`: CoAP over UDP endpoint based on java-coap library. 
 
 So if you start 2 instances you will face port conflict (as all port will be used twice)
 
 The solutions is to also change endpoint port for UDP based on java-coap with option : 
```
      -jp, --java-coap-port=<jlocalPort>
                        Set the local CoAP port of endpoint based on java-coap
                          library.
                        Default: 5685
```

**Comment by PFnord** [comment]
Thanks, I completely overlooked this part :) Works well now
