### ISSUE TITLE
Error Code (Object 3 Recsource 11) 3/0/11

### ISSUE THREAD

**Issue by msmthng** [eclipse-leshan/leshan#1635]
### Question

Hi i have issues with using this resource. By definition this should be a Map with resource instance id and events as values. Each instance should be able to contain more than one errors in my understanding.

But for the value not ArrayList of Numbers can be used (it throws an runtime error) because no lists or similar are supported within the possible types.

do you have a hint how the resource needs to be filled with data to get mor then one error for aa given instance id?

Thx

Martin

**Comment by sbernard31** [comment]
Hi,

Could you give us more details ? Maybe share some code and error you face ?

**Comment by msmthng** [comment]
`Map<Integer, ArrayList<Long>> errorCodes = new HashMap<Integer, ArrayList<Long>>();
//errorCodes.put(0, getErrorCode());
errorCodes.clear();
errorCodes.put(7, (new ArrayList<Long>(Arrays.asList(3010L,3016L))));
errorCodes.put(3, (new ArrayList<Long>(Arrays.asList(1008L, 3004L))));

return ReadResponse.success(resourceid, errorCodes, Type.INTEGER);`

throws following error on the read response:

`org.eclipse.leshan.core.node.LwM2mNodeException: The validated collection contains an element not of type java.lang.Long at index: 0
	at org.eclipse.leshan.core.node.LwM2mNodeUtil.allElementsOfType(LwM2mNodeUtil.java:36)
	at org.eclipse.leshan.core.node.LwM2mMultipleResource.newResource(LwM2mMultipleResource.java:60)
	at org.eclipse.leshan.core.response.ReadResponse.success(ReadResponse.java:121)
	at com.kapschtraffic.digitalobu.client.MyDevice.read(MyDevice.java:140)
	at org.eclipse.leshan.client.resource.ObjectEnabler.doRead(ObjectEnabler.java:218)
	at org.eclipse.leshan.client.resource.BaseObjectEnabler.read(BaseObjectEnabler.java:171)
	at org.eclipse.leshan.client.californium.object.ObjectResource.handleGET(ObjectResource.java:166)
	at org.eclipse.californium.core.CoapResource.handleRequest(CoapResource.java:226)
	at org.eclipse.leshan.core.californium.LwM2mCoapResource.handleRequest(LwM2mCoapResource.java:51)
	at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverRequest(ServerMessageDeliverer.java:106)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:215)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
	at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveRequest(BlockwiseLayer.java:475)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:276)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
	at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:137)
	at org.eclipse.californium.core.network.CoapEndpoint$1.receiveRequest(CoapEndpoint.java:309)
	at org.eclipse.californium.core.network.UdpMatcher$2.run(UdpMatcher.java:270)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:289)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)`

**Comment by sbernard31** [comment]
Error code is a resource Multi-Instance of type INTEGER, see [model](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/e8ab102251c5cc592bcf0bb5e88bf586fbf6a494/3.xml#L190-L212) for more details.

Multi-Instance means that the LWM2M resource have several  LWM2M resource instances. 

So a valid ReadResponse for this resource : 

This should looks like for example : 
```java
Map<Integer, ArrayList<Long>> errorCodes = new HashMap<Integer, ArrayList<Long>>();
errorCodes.put(/* resource instance ID */ 1, /* resource instance value */ 3L); // which means there is issue with GPS
errorCodes.put(/* resource instance ID */ 2, /* resource instance value */ 5L); // device face out of memory error

return ReadResponse.success(resourceid, errorCodes, Type.INTEGER);
```


Looking at your code : 
```java
errorCodes.put(7, (new ArrayList<Long>(Arrays.asList(3010L,3016L))));
errorCodes.put(3, (new ArrayList<Long>(Arrays.asList(1008L, 3004L))));
```

I don't understand what you try to achieve with that. 
Maybe you try to use the error code value as **resource instance ID** ? but  not sure to get the meaning of list as **resource instance value**  ? anyway this doesn't work like this. 

Hope this helps.

**Comment by msmthng** [comment]
Isn't it possible to have 2 gps related errors in parallel? Could it be only one error per instance?

Thx

**Comment by sbernard31** [comment]
> Could it be only one error per instance?

What do you mean by per instance ? 

`Error Code` is about error relative to Device object. (which can only have 1 instance because "Single" Object)

See the resource description : 
>When the single Device Object Instance is initiated, there is only one error code Resource Instance whose value is equal to 0 that means no error. When the first error happens, the LwM2M Client changes error code Resource Instance to any non-zero value to indicate the error type. When any other error happens, a new error code Resource Instance is created. When an error associated with a Resource Instance is no longer present, that Resource Instance is deleted. When the single existing error is no longer present, the LwM2M Client returns to the original no error state where Instance 0 has value 0.
This error code Resource MAY be observed by the LwM2M Server. How to deal with LwM2M Client’s error report depends on the policy of the LwM2M Server. Error codes in between 16 and 32 are specific to the Device and may have different meanings among implementations.]]>

What means the code your share for you ? 
```java
errorCodes.put(7, (new ArrayList<Long>(Arrays.asList(3010L,3016L))));
errorCodes.put(3, (new ArrayList<Long>(Arrays.asList(1008L, 3004L))));
```

**Comment by sbernard31** [comment]
is it clearer ? should we close this issue ?

**Comment by sbernard31** [comment]
I close the issue but feel free to reopen if needed
